/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDealersRouteImport } from './routes/_authenticated/dealers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as ApiPublicPaymentsSummaryRouteImport } from './routes/api/public/payments-summary'
import { Route as ApiPublicDashboardStatsRouteImport } from './routes/api/public/dashboard-stats'
import { Route as ApiPublicContractsSummaryRouteImport } from './routes/api/public/contracts-summary'
import { Route as AuthenticatedContractsIdRouteImport } from './routes/_authenticated/contracts.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealersRoute = AuthenticatedDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsSummaryRoute =
  ApiPublicPaymentsSummaryRouteImport.update({
    id: '/api/public/payments-summary',
    path: '/api/public/payments-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDashboardStatsRoute = ApiPublicDashboardStatsRouteImport.update({
  id: '/api/public/dashboard-stats',
  path: '/api/public/dashboard-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContractsSummaryRoute =
  ApiPublicContractsSummaryRouteImport.update({
    id: '/api/public/contracts-summary',
    path: '/api/public/contracts-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContractsIdRoute =
  AuthenticatedContractsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContractsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/api/public/contracts-summary': typeof ApiPublicContractsSummaryRoute
  '/api/public/dashboard-stats': typeof ApiPublicDashboardStatsRoute
  '/api/public/payments-summary': typeof ApiPublicPaymentsSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/api/public/contracts-summary': typeof ApiPublicContractsSummaryRoute
  '/api/public/dashboard-stats': typeof ApiPublicDashboardStatsRoute
  '/api/public/payments-summary': typeof ApiPublicPaymentsSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dealers': typeof AuthenticatedDealersRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/api/public/contracts-summary': typeof ApiPublicContractsSummaryRoute
  '/api/public/dashboard-stats': typeof ApiPublicDashboardStatsRoute
  '/api/public/payments-summary': typeof ApiPublicPaymentsSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contracts'
    | '/dashboard'
    | '/dealers'
    | '/documents'
    | '/payments'
    | '/contracts/$id'
    | '/api/public/contracts-summary'
    | '/api/public/dashboard-stats'
    | '/api/public/payments-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contracts'
    | '/dashboard'
    | '/dealers'
    | '/documents'
    | '/payments'
    | '/contracts/$id'
    | '/api/public/contracts-summary'
    | '/api/public/dashboard-stats'
    | '/api/public/payments-summary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/dealers'
    | '/_authenticated/documents'
    | '/_authenticated/payments'
    | '/_authenticated/contracts/$id'
    | '/api/public/contracts-summary'
    | '/api/public/dashboard-stats'
    | '/api/public/payments-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicContractsSummaryRoute: typeof ApiPublicContractsSummaryRoute
  ApiPublicDashboardStatsRoute: typeof ApiPublicDashboardStatsRoute
  ApiPublicPaymentsSummaryRoute: typeof ApiPublicPaymentsSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealers': {
      id: '/_authenticated/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof AuthenticatedDealersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments-summary': {
      id: '/api/public/payments-summary'
      path: '/api/public/payments-summary'
      fullPath: '/api/public/payments-summary'
      preLoaderRoute: typeof ApiPublicPaymentsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dashboard-stats': {
      id: '/api/public/dashboard-stats'
      path: '/api/public/dashboard-stats'
      fullPath: '/api/public/dashboard-stats'
      preLoaderRoute: typeof ApiPublicDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contracts-summary': {
      id: '/api/public/contracts-summary'
      path: '/api/public/contracts-summary'
      fullPath: '/api/public/contracts-summary'
      preLoaderRoute: typeof ApiPublicContractsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts/$id': {
      id: '/_authenticated/contracts/$id'
      path: '/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AuthenticatedContractsIdRouteImport
      parentRoute: typeof AuthenticatedContractsRoute
    }
  }
}

interface AuthenticatedContractsRouteChildren {
  AuthenticatedContractsIdRoute: typeof AuthenticatedContractsIdRoute
}

const AuthenticatedContractsRouteChildren: AuthenticatedContractsRouteChildren =
  {
    AuthenticatedContractsIdRoute: AuthenticatedContractsIdRoute,
  }

const AuthenticatedContractsRouteWithChildren =
  AuthenticatedContractsRoute._addFileChildren(
    AuthenticatedContractsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealersRoute: typeof AuthenticatedDealersRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContractsRoute: AuthenticatedContractsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealersRoute: AuthenticatedDealersRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicContractsSummaryRoute: ApiPublicContractsSummaryRoute,
  ApiPublicDashboardStatsRoute: ApiPublicDashboardStatsRoute,
  ApiPublicPaymentsSummaryRoute: ApiPublicPaymentsSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
